spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8080

#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#application:
#  oauth2:
#    client-id: ms-learning-platform
#    client-secret: 7b8059230e0f34af3a6909ab8881f793
#  jwt:
#    access-token-validity: 300 # 5 minutes
#    refresh-token-validity: 1000 # 30m minutes
#
#logging:
#  level:
#    com.example.oauth2_demo: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG