eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
    openfeign:
      okhttp:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/v1/auth/oauth2/.well-known/jwks.json
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: change_me!

application:
  remotes:
    jwks-uri: http://localhost:8081/api/v1/auth/oauth2/.well-known/jwks.json
    oauth2-token-url: http://localhost:8081/api/v1/auth/oauth2/token
  oauth2:
    auth-service-client:
      client-id: auth-service-client
      client-secret: 7b8059230e0f34af3a6909ab8881f793