server:
  port: 8083

  data:
    redis:
      host: localhost
      port: 6379

spring:
  security:
    oauth2:
      client:
        registration:
          ms-learning-platform:
            client-id: ms-learning-platform
            client-secret: 7b8059230e0f34af3a6909ab8881f793

application:
  email-verification-url: http://localhost:8081/api/v1/auth/verify-email
  remotes:
    user-url: http://localhost:8081/api/v1/users
  jwt:
    access-token-validity: 14400 # 2 hours
    refresh-token-validity: 14400 # 2 hours

logging:
  level:
    com.example.oauth2_demo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG