spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
            - id: course-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/courses/**
                - Path=/api/v1/instructor/courses/**
                - Path=/api/v1/admin/courses/**
            - id: auth-service
              uri: lb:http://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

server:
  port: 8081