spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
            - id: course-service
              uri: lb:http://COURSE-SERVICE
              predicates:
                - Path=/api/v1/courses/**
            - id: auth-service
              uri: lb:http://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
            - id: enrollment-service
              uri: lb:http://ENROLLMENT-SERVICE
              predicates:
                - Path=/api/v1/enrollments

management:
  endpoints:
    web:
      exposure:
        include: gateway, routes

server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG