spring:
  data:
    mongodb:
      username: admin
      password: change_me!
      host: localhost
      port: 27017
      database: user
      authentication-database: admin
      auto-index-creation: true

server:
  port: 8082